num_epochs: 10000
batch_size_train: 32
batch_size_val: 32
d_model: 32
d_embedding: 1
nhead: 8
pathway: p2p
test: False
train_test_split: 0.8
save_every: 1
seed: 1337
learning_rate: 0.0001
project: BRIDGE
wandb: True
num_phon_enc_layers: 8
num_orth_enc_layers: 1
num_mixing_enc_layers: 1
num_phon_dec_layers: 2
num_orth_dec_layers: 1
device: cpu
model_path: './models'
dataset_filename: 'data_1.csv'
max_nb_steps: 0
sweep_filename: ""
test_filenames: ""
