# wandb_version: 1
num_epochs: 150
batch_size_train: 64
batch_size_val: 64
d_model: 256
d_embedding: 1
nhead: 2
pathway: o2p
test: false
train_test_split: 1.0
save_every: 9
seed: 1337
learning_rate: 0.0001
project: conntextul_runs
wandb: true
num_phon_enc_layers: 1
num_orth_enc_layers: 1
num_mixing_enc_layers: 1
num_phon_dec_layers: 7
num_orth_dec_layers: 1
device: cpu
model_path: /workspaces/BRIDGE/./models
dataset_filename: /workspaces/BRIDGE/data/kidwords_5000000_020724_unique.csv
max_nb_steps: 20
sweep_filename: ''
test_filenames:
  - /workspaces/BRIDGE/data/tests/test1.csv
  - /workspaces/BRIDGE/data/tests/test2.csv