name: bridge
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - expat=2.6.3
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.7
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - markupsafe==3.0.1
      - mpmath==1.3.0
      - networkx==3.4.1
      - nltk==3.8.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.1.2
      - platformdirs==4.3.6
      - protobuf==5.28.2
      - psutil==6.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dateutil==2.9.0.post0
      - python-stdnum==1.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - sentry-sdk==2.16.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.3
      - torch==2.4.1
      - tqdm==4.66.5
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.18.3
      - git+https://github.com/mathnathan/Traindata.git
