[tool.poetry]
name = "conntextul-conda"
version = "0.1.0"
description = ""
authors = ["erlebach <gordon.erlebach@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.0.1"
pandas = "^2.1.0"
numpy = ">=1.23,<1.26"
pyyaml = "^6.0.1"
wandb = "^0.15.10"
addict = "^2.4.0"
nltk = "^3.8.1"
pytest = "^7.4.2"
matplotlib = "^3.8.0"
pytest-cov = "^4.1.0"
xlsxwriter = "^3.1.9"
tqdm = "^4.66.1"
openpyxl = "^3.1.2"


[tool.poetry.group.dev.dependencies]
coverage = "^7.3.1"
ipykernel = "^6.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
