[project]
name = "bridge"
version = "0.1.0"
description = ""

readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "addict>=2.4.0",
    "nltk==3.8.1",
    "pandas==2.1.2",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
    "torch>=2.4.1",
    "wandb>=0.19.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]
