[tool.poetry]
name = "bridge"
version = "0.1.0"
description = ""
authors = ["Nathan Crock <mathnathan@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12.*,<3.13"
nltk = "3.8.1"
numpy = "1.26.0"
pandas = "2.1.2"
protobuf = "5.28.2"
pydantic = "2.9.2"
pyyaml = "6.0.2"
torch = "2.4.1"
tqdm = "4.66.5"
wandb = "0.18.3"
google-cloud-storage = "3.1.0"

[tool.poetry.group.dev.dependencies]
deptry = "^0.23.0"
pytest = "^8.3.5"
pytest-mock = "^3.14.0"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v -s"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
