program: main.py
method: grid
name: sweep_nathan_40479
metric: 
    goal: minimize
    name: val/loss
parameters: 
    batch_size: {"values": [16,32,64,128]}
    d_model: {"values": [32,64,128,256,512,1024]}
    d_embedding: {"values": [1,2,3]}
    num_epochs: {'values': [20]}
    common_num_layers: {"values": [1,2,3]}
    learning_rate: {"values": [0.0001,0.001]}
    which_dataset: {"values": [40479]}
