# dataset_filepath: 'gs://bridge-ml-training/pretraining/1/input_data_1.pkl'
dataset_filepath: 'data.csv'
# dataset_filepath: 'input_data.pkl'
custom_cmudict_path: 'custom_cmudict.json'
#orthographic_vocabulary_size: 
#phonological_vocabulary_size: 
#max_orth_seq_len: 0
#max_phon_seq_len: 0
