dataset_filepath: 'input_data.pkl'
custom_cmudict_path: 'custom_cmudict.json'
dimension_phon_repr: 31
#orthographic_vocabulary_size: 
#phonological_vocabulary_size: 
#max_orth_seq_len: 0
#max_phon_seq_len: 0