version: 1
disable_existing_loggers: False

formatters:
    standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console_handler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: app/logs/info.log
        maxBytes: 10485760  # 10 MB
        backupCount: 5
        mode: a
    
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: app/logs/debug.log
        maxBytes: 10485760  # 10 MB
        backupCount: 5
        mode: a

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: standard
        filename: app/logs/error.log
        maxBytes: 10485760  # 10 MB
        backupCount: 5
        mode: a

root:
    level: DEBUG
    handlers: [console_handler, info_file_handler, debug_file_handler, error_file_handler]
    propagate: no
