d_model: 1024
d_embedding: 1
nhead: 32
seed: 1337
num_phon_enc_layers: 32
num_orth_enc_layers: 32
num_mixing_enc_layers: 32
num_phon_dec_layers: 32
num_orth_dec_layers: 32

#d_model: 128
#d_embedding: 1
#nhead: 16
#seed: 1337
#num_phon_enc_layers: 8
#num_orth_enc_layers: 1
#num_mixing_enc_layers: 2
#num_phon_dec_layers: 4
#num_orth_dec_layers: 1
