program: app/bin/pretraining_sweep.py
method: bayes
name: sweep_pretraining_0
metric:
  goal: minimize
  name: test_loss
parameters:
  batch_size_train:
    values: [1,2,4,8,16,32, 64]
  learning_rate:
    values: [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1]