num_epochs: 1000
batch_size_train: 64
batch_size_val: 64
train_test_split: 0.9
max_nb_steps: 
learning_rate: 0.0001
training_pathway: p2p
device: cpu #cpu #cuda
save_every: 50
model_artifacts_dir: 'models'
use_wandb: false
weight_decay: 0.01
checkpoint_path: 'models/pretraining/1/model_epoch_50.pth'