num_epochs: 50
batch_size_train: 64
batch_size_val: 64
train_test_split: 0.8
learning_rate: 0.0001
training_pathway: p2p
device: cpu #cpu #cuda
save_every: 50
model_artifacts_dir: 'model_artifacts'
weight_decay: 0.01