num_epochs: 1001
batch_size_train: 64
batch_size_val: 64
train_test_split: 1
max_nb_steps: 
learning_rate: 0.0001
training_pathway: p2p
device: cpu #cpu #cuda
save_every: 50
model_artifacts_dir: 'models'
use_wandb: true
weight_decay: 0.01
model_id: 