FROM nvidia/cuda:12.0.1-cudnn8-runtime-ubuntu22.04

WORKDIR /app

# Install basic build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libffi-dev git python3.10 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install poetry
RUN pip install poetry

# Copy poetry files and install dependencies
COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev

# Copy the rest of the application
COPY . /app


