FROM nvidia/cuda:12.0.1-cudnn8-runtime-ubuntu22.04

WORKDIR /app

# Set DEBIAN_FRONTEND to noninteractive to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install basic build dependencies and Python 3.12 from deadsnakes PPA
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    git \
    curl \
    software-properties-common \
    tzdata && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-venv python3.12-dev python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Create python symlink for python3
RUN ln -s /usr/bin/python3.12 /usr/bin/python

# Install CUDA Toolkit (which includes CUPTI)
RUN apt-get update && \
    apt-get install -y cuda-toolkit-12-0 gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ls -la /root/.local/bin
# Add Poetry to PATH manually
ENV PATH="${PATH}:/root/.local/bin"

# Copy poetry files and install dependencies
COPY pyproject.toml /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-root

# Copy the rest of the application
COPY . /app
